production:
  host: redis-instance
  port: 6379
  db: 0
  readthis_db: 1
  sidekiq_db: 2

staging:
  host: redis-instance
  port: 6379
  db: 0
  readthis_db: 1
  sidekiq_db: 2

development:
  host: localhost
  port: 6379
  db: 4
  readthis_db: 5
  sidekiq_db: 6

test:
  host: localhost
  port: 6379
  db: 4
  readthis_db: 5
  sidekiq_db: 6
